Repository openmaptiles/openmaptiles-tools, pull requests merged in 2019-10, with the labels that each got.

#65 Fix mapping diagram generation for type_mappings
  openmaptiles/diagram.py
Labels: bug

#62 Use connection pool and asyncpg
  bin/postserve
  openmaptiles/postserve.py
  requirements.txt
Labels: enhancement

#67 refresh materialized views in parallel utility
  .dockerignore
  Dockerfile
  Makefile
  README.md
  bin/run-sql
  docker-run.sh
  openmaptiles/utils.py
  requirements.txt
  test/__init__.py
  test/test_utils.py
Labels: enhancement

#70 Stop DB connection on client gettile abort
  bin/postserve
  openmaptiles/postserve.py
Labels: enhancement, postserve

#58 Refactoring MVT, Postserve, validates fields against live PG
  bin/generate-sqltomvt
  bin/postserve
  openmaptiles/language.py
  openmaptiles/postserve.py
  openmaptiles/sqltomvt.py
  openmaptiles/tileset.py
Labels: enhancement, postserve
